// @no-log
GET {{host}}
Accept: application/json

### GET request with a header
// @no-log
GET {{host}}/healthcheck
Accept: application/json

### POST request with a header
// @no-log
POST {{host}}
Accept: */*
Content-Type: application/json

{
  "foo": "bar"
}